### PR TITLE
Remove header filter from localisation grid field

### PR DESCRIPTION
**Pull request by satrun77**
## Issues

- https://github.com/tractorcow-farm/silverstripe-fluent/issues/875

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

### CODE REVIEW

**Comment by tractorcow** [comment]
Incorrect target branch?

**Comment by satrun77** [comment]
> Incorrect target branch?

I targeted `7.1`. Which branch do you want it to be?

**Comment by tractorcow** [comment]
No that's ok, I just saw lots of unrelated commit messages. It seems fine now.

**Review by tractorcow — APPROVED** [review]

**Comment by satrun77** [comment]
> No that's ok, I just saw lots of unrelated commit messages. It seems fine now.

Ah yes. I saw that and rebased before I saw your comment :) Thanks for looking into this PR

**Comment by tractorcow** [comment]
fixed and thanks for the contribution.

**Comment by GuySartorelli** [comment]
Didn't see this PR in time - but it should probably be conditional on whether `BasicSearchContext` is available (i.e. whether framework 5.2+ is used) - see https://docs.silverstripe.org/en/5/developer_guides/forms/using_gridfield_with_arbitrary_data/#arraydata-filter

**Pull request merged**
