### PR TITLE
Revert "FIX Fluent now respects existing base URL prefixes in URL segment fields when no fluent domain exists"

### PR DESCRIPTION
**Pull request by tractorcow**
Reverts tractorcow-farm/silverstripe-fluent#523

Resolves https://github.com/tractorcow-farm/silverstripe-fluent/issues/538

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
BTW @tractorcow - you'll have to delete the branches off of packagist - I don't have maintainer status on packagist for this repo.

**Comment by robbieaverill** [comment]
Do we need to reopen https://github.com/silverstripe/silverstripe-subsites/issues/416 now?

**Comment by ScopeyNZ** [comment]
Yep! (I did already 😉)

**Comment by tractorcow** [comment]
Oh sorry, yes I should be careful about those branches.

@ScopeyNZ I'll add you to packagist :P

**Comment by tractorcow** [comment]
Done https://packagist.org/packages/tractorcow/silverstripe-fluent

**Pull request merged**
