### PR TITLE
API phpunit 9 support

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10019

Unit tests pass locally with phunit 9.5.10

Free GitHub action CI to replace Travis CI (which no longer runs) - however I don't have enough permissions on this repo for it to trigger.

Tag 4.6.0 upon merge

### CODE REVIEW

**Comment by tractorcow** [comment]
Nice job, although the 4 branch is a bit out of date (we are on 5, ready to release 6 soon I think).

**Comment by tractorcow** [comment]
image

**Comment by tractorcow** [comment]
Looks like there was an error

```
PHP Fatal error:  Trait 'DMS\PHPUnitExtensions\ArraySubset\ArraySubsetAsserts' not found in /home/runner/work/silverstripe-fluent/silverstripe-fluent/vendor/silverstripe/reports/tests/ReportAdminTest.php on line 14
```

**Comment by emteknetnz** [comment]
Yes, it's currently in the middle of a somewhat messy transition all updating the dependencies under silverstripe/recipe-kitchen-sink from phpunit5 to phpunit 9 - https://github.com/silverstripe/silverstripe-framework/issues/10019

**Pull request merged**
