### PR TITLE
Merge branch '6' into 7

### PR DESCRIPTION
**Pull request by GuySartorelli**
The gha-merge-up action won't merge up because of a merge conflict when merging up from the `6` branch to the `7.1` branch: https://github.com/tractorcow-farm/silverstripe-fluent/actions/runs/9218330417/job/25361687967

I lack the required level of access to push directly to the 7 branch, so the only way I can resolve it is with a PR.

The conflict on `FluentExtension` is just the same change being made in both branches.

For the conflict in `InitialPageLocalisationTask`, looking at the difference between https://github.com/tractorcow-farm/silverstripe-fluent/commits/7.1/src/Task/InitialPageLocalisationTask.php and https://github.com/tractorcow-farm/silverstripe-fluent/commits/6/src/Task/InitialPageLocalisationTask.php it's clear the resolution is to keep the changes from `6`.

I'd like @tractorcow to review this one, since there's a lot of functionality here being merged up between majors and I'm not familiar with these features enough to know if they're all okay for `7.x`.

## Issue
- https://github.com/silverstripe/.github/issues/251

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Retargetted to the `7` branch - there's stuff here that looks like it shouldn't be in a patch release.

If this gets merged, note that the merge-ups action will continue failing until the October minor release, since it will keep trying to merge `6` into `7.1` until then.

**Review by tractorcow — APPROVED** [review]

**Comment by tractorcow** [comment]
Approved, any time.

**Comment by emteknetnz** [comment]
@GuySartorelli merge conflict

**Comment by GuySartorelli** [comment]
Merge conflict in `CachableModel.php` was just a use statement for `Director`, which is not needed so I've removed it.
I redid the merge in order to resolve it so the "compare" link will show more changes than just that - but the end result is still the same. It's merging everything from `6` into `7`.

**Review by emteknetnz — APPROVED** [review]

**Pull request merged**
