### PR TITLE
Fixed  missing -> operator.

### PR DESCRIPTION
**Pull request by taoceanz**
Missing -> operator in migration task causing fatal error when Locale not found.

### CODE REVIEW

**Comment by taoceanz** [comment]
Cool, thanks Robbie.

**Comment by taoceanz** [comment]
Is this PR able to be merged into 4.3, and 4.4? Running the migration task in either of those version encounters issues because `$instanceID` doesn't exist.

**Comment by robbieaverill** [comment]
All done @taoceanz

**Comment by taoceanz** [comment]
Wicked! Thanks @robbieaverill

**Comment by taoceanz** [comment]
@robbieaverill it's not possible to merge this into existing tags, is it? Requiring versions of this module via Composer doesn't contain changes from this PR. Alternatively, do you know when tag 4.4.2 will be released and available to pull via Composer?

**Comment by tractorcow** [comment]
I'll tag a new release soon.

**Comment by taoceanz** [comment]
@tractorcow Thanks!

**Comment by tractorcow** [comment]
https://github.com/tractorcow-farm/silverstripe-fluent/releases/tag/4.4.2

**Comment by taoceanz** [comment]
Wicked, thank you.

**Pull request merged**
