### PR TITLE
#582 Alternate href added to $MetaTags even if no localised version i…

### LINKED ISSUE #582: Alternate href added to $MetaTags even if no localised version is published
Fluent always adds alternate hrefs to the $MetaTags, even though there is no localised version in another language published.

How to reproduce :
1> Set frontend_publish_required to true in config
2> Add 2 locales
3> Add and publish page in the base locale, but do not publish it in the 2nd locale
4> Look at output of $MetaTags of base language page, it will add an alternate link containing just the base domain + locale, without a page segment. E.g. :  www.domain.com/en

### PR DESCRIPTION
**Pull request by Cas-terRiet-Directlease**
Fix #582 Alternate href added to $MetaTags even if no localised version is published bug

### CODE REVIEW

**Comment by Cas-terRiet-Directlease** [comment]
I think this is a fix for this problem, I only can't figure out what the problem is within the PHP test. can you guys maybe look at the code to see what the problem is?

**Comment by tractorcow** [comment]
In `develop` branch there is a new helper you can use here. `RecordLocale`, and the best method here is the `IsPublished` method, which will check if a record is both published, and visible in that locale. It includes all the business logic you need, including handling both localisation, filtering, and configuration based rules.

**Comment by tractorcow** [comment]
https://github.com/tractorcow-farm/silverstripe-fluent/blob/develop/src/Model/RecordLocale.php#L252

**Comment by tractorcow** [comment]
Possibly we could do this

```diff
-<% if $LinkingMode != 'invalid' %>
+<% if $IsPubilshed %>
```

In FluentSiteTree_MetaTags.ss

**Comment by tractorcow** [comment]
@Cas-terRiet-Directlease test `develop` branch; Let me know if you are happy with this fix.

https://github.com/tractorcow-farm/silverstripe-fluent/commit/ea8619a5d24280b14fbf47716bd6a34a0860500f

Note: Develop isn't stable yet, so be careful about updating your site to this version. :)

We can additionally post another fix to the prior version, but I'll try to keep the fixes as close to one another as possible.

**Comment by Cas-terRiet-Directlease** [comment]
@tractorcow this fix also works for us, thank you :D

**Comment by tractorcow** [comment]
Thanks @Cas-terRiet-Directlease ; I'm going to close this for now, because I'd like to prioritise upgrading over changing current behaviour. I will see if I can back-port the fix without possibly breaking existing logic too much. :)

**Comment by tractorcow** [comment]
note: Anyone can get the new version with `dev-develop` as their composer dependency.

**Pull request closed without merging**
