### PR TITLE
MNT Use travis shared config, use sminnee/phpunit

### PR DESCRIPTION
**Pull request by emteknetnz**
Targets 5.0 branch

### CODE REVIEW

**Comment by tractorcow** [comment]
Can we justify why we have forked phpunit? I'm not aware of the background around that decision.

**Comment by emteknetnz** [comment]
sminnee/phpunit is a fork of phpunit 5.7 that includes php8 compatibility

Idealy we'd be running phpunit ^9 though we haven't yet done the work to get silverstripe compatible with that

**Comment by tractorcow** [comment]
sounds fair, I'll accept that. Hopefully we can upgrade phpunit and not need this. :)

**Review by dnsl48 — APPROVED** [review]
looks good to me

**Comment by dnsl48** [comment]
Assuming the broken tests are caused by the increased code coverage and not this PR.

**Pull request merged**
