### PR TITLE
BUG: Fix Travis setup to run with correct requirements.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
## BUG: Fix Travis setup to run with correct requirements

* Fix Travis setup to run with correct requirements to match composer requirements
* Fix breaking unit tests

### CODE REVIEW

**Comment by mfendeksilverstripe** [comment]
The travis config is now updated but it looks like we have some `PGSQL` issues.

**Comment by tractorcow** [comment]
Yeah there is code in there that's generating non-pgsql SQL :)

ansi-sql identifiers should always be double quoted. MySQL just doesn't complain about it, but it's still incorrect.

**Comment by tractorcow** [comment]
See FluentVersionedExtension::hasArchiveInLocale(). It's using unquoted tables.

**Comment by mfendeksilverstripe** [comment]
@tractorcow Tests are all green, please review.

**Review by chrispenny — COMMENTED** [review]
The change seems fine to me (if these areas are covered by unit tests).

**Pull request merged**
