### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by bumbus**
- replace magic var `__CLASS__` with `__TRAIT__` in traits
- added de.yml

### CODE REVIEW

**Comment by tractorcow** [comment]
Just one unit test to patch :) I might go in and fix it myself though.

What an amazing amount of quality work, and in such short time since 5 alpha.

**Comment by bumbus** [comment]
@tractorcow Sorry I did not run the tests. But anyway, these actions / menu  really is an enhancement. Thank you very much for bringing this into the game. Let me know if you need further help on this.

**Comment by tractorcow** [comment]
Thanks @bumbus that's fine that's what unit testing is for. Sometimes it shows weaknesses in the tests. :) I will review and take it from here on thanks.

**Comment by tractorcow** [comment]
Test breakages were because the en.yml was out of date. Easy fix.

**Comment by tractorcow** [comment]
This is now all included in alpha3 https://github.com/tractorcow-farm/silverstripe-fluent/releases/tag/5.0.0-alpha3

**Pull request merged**
