### PR TITLE
Update FluentExtension.php

### PR DESCRIPTION
**Pull request by mikey-harveycameron**
skip empty 'where' clauses.
just trying to make this available for SS4.

### CODE REVIEW

**Comment by tractorcow** [comment]
Do you know when this value is ever blank? Is there another error that we are ignoring in this case? further upstream? My worry is that there's a condition we are handling wrong, and just ignoring it instead.

**Comment by tractorcow** [comment]
So this could occur if you had a condition like

```php
$query->where(['' => 3]); // Not a valid condition, but is accepted anyway
```

**Review by tractorcow — APPROVED** [review]

**Comment by tractorcow** [comment]
No harm in the merge, but it'd be good to track down the cause please if you can add some more context in your own time. :)

**Comment by mikey-harveycameron** [comment]
Could you update this branch with a new tag or something please, so that composer update can reach it... maybe like 6.0.1? (Not quite sure how this works, my apologies.)

**Comment by mikey-harveycameron** [comment]
FYI I was able to target it with composer using "6.x-dev"

**Pull request merged**
