### PR TITLE
API Replace Extension subclasses

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/11050

### CODE REVIEW

**Review by tractorcow — APPROVED** [review]

**Comment by tractorcow** [comment]
Sure, if that's what the new silverstripe has changed, sounds good to me.

**Review by GuySartorelli — COMMENTED** [review]
LGTM, but will hold this one off for last since it has failing tests. Will rerun CI after everything else is merged.

**Comment by GuySartorelli** [comment]
CI still failing - I would have said these look unrelated, except the full kitchen sink run was passing so I'd expect this to pass now too.

**Comment by emteknetnz** [comment]
Have updated unit test to use an equivalent public API

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Pull request merged**
