### PR TITLE
MNT Run module-standardiser

### PR DESCRIPTION
**Pull request by GuySartorelli**
This pull-request was created automatically by [module-standardiser](https://github.com/silverstripe/module-standardiser)

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Don't merge yet - I'll make the changes to satisfy the new PHPStan linting rule.

**Comment by tractorcow** [comment]
I like the phpstan inclusion.

**Comment by tractorcow** [comment]
Check your invites added you as maintainer

**Comment by GuySartorelli** [comment]
There we go, that should go green now.

> I like the phpstan inclusion.

Yeah we're slowly getting into some more robust code standards. For now we're only applying a single custom PHPstan rule, but it opens the door to progressively having stricter standards.

> Check your invites added you as maintainer

Awesome, thank you! 💙

**Review by emteknetnz — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Approved by a core committer, so self-merging.

**Pull request merged**
