### PR TITLE
DEP Limit PHP support for CMS 6

### PR DESCRIPTION
**Pull request by GuySartorelli**
## Issue
- https://github.com/silverstripe/.github/issues/297

### CODE REVIEW

**Comment by tractorcow** [comment]
PHP 8.3 has a bunch of linting errors when using `self::` in extensions. Do you want to address those in this same PR?

**Comment by GuySartorelli** [comment]
The linting errors aren't related to PHP 8.3. They have been addressed on the `7` branch in https://github.com/tractorcow-farm/silverstripe-fluent/pull/867 - that just needs to be merged up for phplinting to be happy so that will be dealt with separately.

The trailing slash failures have also already been dealt with (in https://github.com/tractorcow-farm/silverstripe-fluent/pull/872) and that just needs to be merged up.

I'll merge those up soon and rebase this PR on top of it, so we can see if there are any remaining CI failures to deal with.

**Comment by tractorcow** [comment]
Sounds good, go ahead and do those merges as you see fit.

**Comment by GuySartorelli** [comment]
Tried to push a merge up to the `7` branch and got an error "Changes must be made through a pull request". So I've raised https://github.com/tractorcow-farm/silverstripe-fluent/pull/877

After that's merged I'll need to do another one merging `7` up to `8`.

**Comment by tractorcow** [comment]
7 has been merged.

**Comment by GuySartorelli** [comment]
Thanks! I've created https://github.com/tractorcow-farm/silverstripe-fluent/pull/878 merging `7` to `8`.

**Comment by tractorcow** [comment]
I've left that PR approved; you can merge when ready friend.

**Comment by GuySartorelli** [comment]
Merged that, and rebased this on top. And it's green! 🎉

**Review by tractorcow — APPROVED** [review]

**Pull request merged**
