### PR TITLE
Use the locale's URLSegment as default badge label

### PR DESCRIPTION
**Pull request by JorisDebonnet**
See the comments since April 2019 on #389. Improves #510.

### CODE REVIEW

**Comment by robbieaverill** [comment]
@clarkepaul are you happy with this becoming the new default? It'd be `en_NZ` rather than `NZ`, for example

**Comment by robbieaverill** [comment]
Actually I think this is an enhancement, so we should target the master branch instead. Would you mind changing the target branch and rebasing the PR?

**Comment by JorisDebonnet** [comment]
> 
> 
> @clarkepaul are you happy with this becoming the new default? It'd be `en_NZ` rather than `NZ`, for example

That's assuming you leave the default URLSegment, of course. Personally, I like using /en/ etc in the URLs, and then the labels also just say EN.

**Comment by robbieaverill** [comment]
Sorry yeah I was thinking of the full locale. I think that's OK, because it's probably been customised so it looks better than the default locale

**Comment by JorisDebonnet** [comment]
Space removed and base changed. I guess this means it will only go live in Fluent 4.3... aww.

**Comment by robbieaverill** [comment]
Thanks, yeah - but you can use `4.3.x-dev` in your projects until it's ready

**Comment by JorisDebonnet** [comment]
Is anything else needed to make this fit for merging?

**Comment by robbieaverill** [comment]
The bump was enough, thank you

**Pull request merged**
