### PR TITLE
Update contributing guidelines

### PR DESCRIPTION
**Pull request by tractorcow**
Closes https://github.com/tractorcow-farm/silverstripe-fluent/issues/587

cc @chillu

### CODE REVIEW

**Comment by chillu** [comment]
Yeah that all sounds reasonable, thanks for taking the time to write it up! Do you see a difference between "maintainers" and the "contributing team" (as you phrased it)? Technically, everyone participating in this module is a contributor, I think calling it a "maintainer" is a bit less ambiguous? In core, we've carved out that role of a "contributing committer", but that's also a bit strange naming.

**Comment by tractorcow** [comment]
Na it's just a wording. :) I'll consolidate to use the popular nomenclature. :)

**Comment by chillu** [comment]
OK I've merged, as a way of +1'ing. I'll also circulate it with the product devs here at the mothership.

**Comment by tractorcow** [comment]
Thanks :D

**Comment by brynwhyman** [comment]
FWIW, I think this a nice set of guidelines! Totally reasonable.

**Pull request merged**
